name: Deploy Miden Assembly Playground

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install WASM toolchain 🛠️
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Install and Build 🔧
        run: |
          cd playground
          npm install
          npm run build:miden
          npx webpack --config webpack.config.js

      - name: Add 404 fallback for SPA
        run: cp playground/dist/index.html playground/dist/404.html

      - name: Deploy to GitHub Pages 🚀
        if: github.ref_name == 'main' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playground/dist
          cname: playground.miden.io
