name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      - name: Install WASM
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install and Build 🔧 
        run: |
          npm install
          npm run preinstall
          npm run build
          npx webpack

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
